import os
import re
from typing import List, Dict, Any, Tuple
from src.config import config
from src.pinyin_utils import prepare_word_tuple
from src.audio_generator import generate_chinese_voice

def generate_scene_code(
    words: List[Dict[str, Any]],
    topic: str = "HSK 1-2 • TỪ VỰNG CƠ BẢN",
    level: str = "HSK 1-2",
    scene_name: str = "ModernVocabCNQuizScene",
    cover_path: str = ""
) -> str:
    """
    Generates standalone Python/Manim script code for VocabCNQuiz:
    Hero Question: Chinese Hanzi + Pinyin -> 5s Countdown -> Reveal Vietnamese Meaning + Audio TTS.
    """
    clean_topic = topic.replace('"', '\\"')
    
    words_data = []
    for item in words:
        if isinstance(item, dict):
            h = item.get("hanzi", "")
            fp = item.get("pinyin", "")
            hp = item.get("hidden_pinyin", "")
            m = item.get("meaning", "")
        elif isinstance(item, (list, tuple)):
            h = item[0] if len(item) > 0 else ""
            fp = item[1] if len(item) > 1 else ""
            hp = item[2] if len(item) > 2 else ""
            m = item[3] if len(item) > 3 else ""
        else:
            continue
            
        if h:
            if not fp or not hp:
                _, fp_calc, hp_calc = prepare_word_tuple(h, fp, hp)
                fp = fp or fp_calc
                hp = hp or hp_calc
                
            voice_path = generate_chinese_voice(h)
            words_data.append({
                "hanzi": h,
                "pinyin": fp,
                "hidden_pinyin": hp,
                "meaning": m or h,
                "voice": voice_path
            })
            
    words_code = repr(words_data)
    
    code = f'''# Auto-generated by lelehoctiengtrung VocabCNquiz scene generator
from manim import *
import os

config.pixel_width = 1080
config.pixel_height = 1920
config.frame_width = 9.0
config.frame_height = 16.0

CHINESE_FONT = "{config.chinese_font}"
VIETNAMESE_FONT = "Arial"

class {scene_name}(Scene):
    def construct(self):
        words = {words_code}
        total_words = len(words)
        topic_title = "{clean_topic}"

        # 0. High-CTR Cover Thumbnail (0.75s Cover at 00:00 for TikTok / Shorts / Reels)
        cover_path = "{cover_path}"
        if os.path.exists(cover_path):
            cover_img = ImageMobject(cover_path)
            cover_img.set_height(config.frame_height)
            cover_img.set_width(config.frame_width)
            self.add(cover_img)
            self.wait(0.75)
            self.remove(cover_img)

        # 1. Background Image
        bg_path = "{os.path.join(config.base_dir, 'assets/images/background.jpg')}"
        if os.path.exists(bg_path):
            bg_image = ImageMobject(bg_path)
            bg_image.set_height(config.frame_height)
            bg_image.set_width(config.frame_width)
            self.add(bg_image)
            
        dark_overlay = Rectangle(
            width=config.frame_width,
            height=config.frame_height,
            fill_color="#030712",
            fill_opacity=0.50,
            stroke_width=0
        )
        self.add(dark_overlay)

        # 2. Top Header Pill
        pill_text = Text(
            topic_title.upper(),
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#064e3b",
            weight=BOLD
        )
        pill_bg = RoundedRectangle(
            corner_radius=0.35,
            width=max(pill_text.width + 0.8, 3.6),
            height=0.68,
            fill_color="#10b981",
            fill_opacity=0.98,
            stroke_color="#6ee7b7",
            stroke_width=1.5
        ).move_to(UP * 6.7)
        pill_text.move_to(pill_bg.get_center())
        header_pill = VGroup(pill_bg, pill_text)

        # 3. Top Mode Box: "Đoán nghĩa trong 5s"
        mode_card = RoundedRectangle(
            corner_radius=0.25,
            width=5.2,
            height=0.9,
            fill_color="#0b0f19",
            fill_opacity=0.88,
            stroke_color="#334155",
            stroke_width=1.5
        ).next_to(pill_bg, DOWN, buff=0.22)
        
        mode_title = Text(
            "Đoán nghĩa trong 5s",
            font=VIETNAMESE_FONT,
            font_size=26,
            color="#34d399",
            weight=BOLD
        ).move_to(mode_card.get_center())
        
        header_mode = VGroup(mode_card, mode_title)
        self.play(FadeIn(header_pill, shift=DOWN*0.3), FadeIn(header_mode, shift=DOWN*0.3), run_time=0.6)

        # 4. Bottom Footer Floating Card: Logo + "lelehoctiengtrung"
        footer_card = RoundedRectangle(
            corner_radius=0.3,
            width=7.4,
            height=1.25,
            fill_color="#090d16",
            fill_opacity=0.88,
            stroke_color="#1e293b",
            stroke_width=1.5
        ).move_to(DOWN * 6.3)

        avatar_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(avatar_path):
            avatar_img = ImageMobject(avatar_path).set_height(0.85)
            avatar_bg = RoundedRectangle(corner_radius=0.2, width=0.9, height=0.9, fill_color="#059669", fill_opacity=0.3, stroke_width=0)
            avatar_group = Group(avatar_bg, avatar_img).move_to(footer_card.get_left() + RIGHT * 0.75)
        else:
            avatar_group = Dot(radius=0.4, color=GREEN_D).move_to(footer_card.get_left() + RIGHT * 0.75)

        footer_title = Text("lelehoctiengtrung", font=VIETNAMESE_FONT, font_size=32, color=WHITE, weight=BOLD)
        footer_title.next_to(avatar_group, RIGHT, buff=0.35)

        footer_base = Group(footer_card, avatar_group, footer_title)
        self.play(FadeIn(footer_base, shift=UP*0.3), run_time=0.5)

        # 5. Words Loop
        for idx, w in enumerate(words, start=1):
            hanzi = w["hanzi"]
            pinyin_full = w["pinyin"]
            meaning = w["meaning"]
            voice_file = w.get("voice", "")

            # Word counter with emotional curve badge
            icon_suffix = " ⚡" if idx == 4 else (" 🔥" if idx == 5 else "")
            counter_color = "#34d399" if idx == 4 else ("#f87171" if idx == 5 else "#94a3b8")
            counter_text = Text(
                f"Từ {{idx}}/{{total_words}}{{icon_suffix}}",
                font=VIETNAMESE_FONT,
                font_size=26,
                color=counter_color,
                weight=BOLD if idx >= 4 else SEMIBOLD
            )
            counter_text.move_to(footer_card.get_right() + LEFT * 1.0)
            self.play(FadeIn(counter_text, run_time=0.2))

            # Main Question Card
            center_card = RoundedRectangle(
                corner_radius=0.45,
                width=7.4,
                height=6.8,
                fill_color="#090d16",
                fill_opacity=0.88,
                stroke_color="#334155",
                stroke_width=1.5
            ).move_to(UP * 0.3)

            # 1. Question Hero: Chữ Hán to
            hz_text = Text(
                hanzi,
                font=CHINESE_FONT,
                font_size=120,
                color=WHITE,
                weight=BOLD
            ).move_to(center_card.get_top() + DOWN * 1.4)
            if hz_text.width > 6.4:
                hz_text.scale_to_fit_width(6.4)
            
            # 2. Pinyin
            py_text = Text(
                pinyin_full,
                font=VIETNAMESE_FONT,
                font_size=55,
                color="#38bdf8",
                weight=BOLD
            ).next_to(hz_text, DOWN, buff=0.3)
            if py_text.width > 6.4:
                py_text.scale_to_fit_width(6.4)

            # 3. Placeholder chờ đoán nghĩa
            vn_placeholder = Text(
                "[ Nghĩa tiếng Việt là gì? ]",
                font=VIETNAMESE_FONT,
                font_size=42,
                color="#34d399",
                weight=SEMIBOLD
            ).next_to(py_text, DOWN, buff=0.5)

            # 4. Countdown 5 giây
            time_label = Text("TIME", font=VIETNAMESE_FONT, font_size=30, color="#94a3b8", weight=BOLD)
            timer_num = Text("5", font=VIETNAMESE_FONT, font_size=54, color=WHITE, weight=BOLD)
            timer_group = VGroup(time_label, timer_num).arrange(RIGHT, buff=0.25).next_to(vn_placeholder, DOWN, buff=0.5)

            # Progress Bar Track
            bar_width = 5.4
            bar_track = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#1e293b",
                fill_opacity=0.8,
                stroke_width=0
            ).next_to(timer_group, DOWN, buff=0.35)

            active_bar = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#10b981",
                fill_opacity=1.0,
                stroke_width=0
            ).move_to(bar_track.get_center())

            quiz_mobjects = VGroup(center_card, hz_text, py_text, vn_placeholder, timer_group, bar_track, active_bar)
            self.play(FadeIn(quiz_mobjects, shift=UP*0.2), run_time=0.4)

            # 5s countdown
            tick_file = "{os.path.join(config.base_dir, 'assets/audio/tick.mp3')}"
            total_seconds = 5
            for s in range(total_seconds, 0, -1):
                if os.path.exists(tick_file):
                    try:
                        self.add_sound(tick_file)
                    except Exception:
                        pass
                
                fraction_left = (s - 1) / total_seconds
                new_bar_width = max(bar_width * fraction_left, 0.01)
                
                new_active_bar = RoundedRectangle(
                    corner_radius=0.08,
                    width=new_bar_width,
                    height=0.16,
                    fill_color="#10b981" if s > 2 else "#f43f5e",
                    fill_opacity=1.0 if s > 1 else 0.0,
                    stroke_width=0
                ).move_to(bar_track.get_center()).align_to(bar_track, LEFT)
                
                display_num = str(s - 1) if s > 1 else "0"
                new_timer_num = Text(display_num, font=VIETNAMESE_FONT, font_size=54, color=WHITE if s > 2 else "#f43f5e", weight=BOLD)
                new_timer_num.move_to(timer_num.get_center())

                self.play(
                    Transform(active_bar, new_active_bar),
                    Transform(timer_num, new_timer_num),
                    run_time=0.9,
                    rate_func=linear
                )
                self.wait(0.1)

            # HẾT 5s: Chuông báo kết thúc đếm ngược
            bell_file = "{os.path.join(config.base_dir, 'assets/audio/ding.mp3')}"
            if not os.path.exists(bell_file):
                bell_file = "{config.bell_audio_path}"
            if os.path.exists(bell_file):
                try:
                    self.add_sound(bell_file)
                except Exception:
                    pass

            self.play(FadeOut(timer_group), FadeOut(bar_track), FadeOut(active_bar), FadeOut(vn_placeholder), run_time=0.15)

            # Hiện Đáp án Nghĩa Tiếng Việt
            ans_meaning = Text(
                meaning,
                font=VIETNAMESE_FONT,
                font_size=85,
                color="#34d399",
                weight=BOLD
            ).move_to(center_card.get_center() + DOWN * 1.0)
            if ans_meaning.width > 6.4:
                ans_meaning.scale_to_fit_width(6.4)

            self.play(FadeIn(ans_meaning, shift=UP*0.2), run_time=0.45)

            # Sau tiếng chuông 0.5s mới phát âm thanh mẫu
            self.wait(0.75)

            if voice_file and os.path.exists(voice_file):
                try:
                    self.add_sound(voice_file)
                except Exception:
                    pass

            # Giữ 2.2 giây để người xem đọc theo
            self.wait(2.2)

            # Clear card
            self.play(
                FadeOut(center_card),
                FadeOut(hz_text),
                FadeOut(py_text),
                FadeOut(ans_meaning),
                FadeOut(counter_text),
                run_time=0.35
            )

        # End Screen CTA
        end_card = RoundedRectangle(
            corner_radius=0.45,
            width=7.6,
            height=5.8,
            fill_color="#090d16",
            fill_opacity=0.94,
            stroke_color="#10b981",
            stroke_width=2.0
        ).move_to(UP * 0.3)

        logo_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(logo_path):
            logo_img = ImageMobject(logo_path).set_height(1.3)
            logo_bg = RoundedRectangle(
                corner_radius=0.3,
                width=1.45,
                height=1.45,
                fill_color="#0f172a",
                fill_opacity=0.9,
                stroke_color="#10b981",
                stroke_width=1.5
            )
            center_logo = Group(logo_bg, logo_img).move_to(end_card.get_top() + DOWN * 1.1)
        else:
            center_logo = Dot(radius=0.6, color=GREEN_D).move_to(end_card.get_top() + DOWN * 1.1)

        end_title = Text(
            "BẠN ĐÚNG MẤY TỪ?",
            font=VIETNAMESE_FONT,
            font_size=42,
            color="#34d399",
            weight=BOLD
        ).next_to(center_logo, DOWN, buff=0.35)

        end_cta = Text(
            "Bình luận số câu đúng bên dưới nhé! 👇",
            font=VIETNAMESE_FONT,
            font_size=28,
            color=WHITE,
            weight=SEMIBOLD
        ).next_to(end_title, DOWN, buff=0.25)

        end_sub = Text(
            "Follow @lelehoctiengtrung để học mỗi ngày 🚀",
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#94a3b8",
            weight=NORMAL
        ).next_to(end_cta, DOWN, buff=0.35)

        end_mobjects = Group(end_card, center_logo, end_title, end_cta, end_sub)
        self.play(FadeIn(end_mobjects, shift=UP*0.3), run_time=0.6)
        self.wait(2.5)
'''
    return code

def create_scene_file(
    words: List[Dict[str, Any]],
    topic: str,
    level: str,
    output_py_path: str,
    scene_name: str = "ModernVocabCNQuizScene",
    cover_path: str = ""
) -> str:
    os.makedirs(os.path.dirname(output_py_path), exist_ok=True)
    code = generate_scene_code(words, topic, level, scene_name, cover_path)
    with open(output_py_path, "w", encoding="utf-8") as f:
        f.write(code)
    return output_py_path
