import os
import re
from typing import List, Dict, Any, Tuple
from src.config import config
from src.pinyin_utils import prepare_word_tuple
from src.audio_generator import generate_chinese_voice

def generate_scene_code(
    words: List[Dict[str, Any]],
    topic: str = "HSK 1-2 • TỪ VỰNG CƠ BẢN",
    level: str = "HSK 1-2",
    scene_name: str = "ModernPinyinQuizScene"
) -> str:
    """
    Generates standalone Python/Manim script code matching user's exact storyboard and layout.
    """
    clean_topic = topic.replace('"', '\\"')
    
    words_data = []
    for item in words:
        if isinstance(item, dict):
            h = item.get("hanzi", "")
            fp = item.get("pinyin", "")
            hp = item.get("hidden_pinyin", "")
            m = item.get("meaning", "")
        elif isinstance(item, (list, tuple)):
            h = item[0] if len(item) > 0 else ""
            fp = item[1] if len(item) > 1 else ""
            hp = item[2] if len(item) > 2 else ""
            m = item[3] if len(item) > 3 else ""
        else:
            continue
            
        if h:
            if not fp or not hp:
                _, fp_calc, hp_calc = prepare_word_tuple(h, fp, hp)
                fp = fp or fp_calc
                hp = hp or hp_calc
                
            voice_path = generate_chinese_voice(h)
            words_data.append({
                "hanzi": h,
                "pinyin": fp,
                "hidden_pinyin": hp,
                "meaning": m or h,
                "voice": voice_path
            })
            
    words_code = repr(words_data)
    
    code = f'''# Auto-generated by lelehoctiengtrung_pinyin modern scene generator
from manim import *
import os

config.pixel_width = 1080
config.pixel_height = 1920
config.frame_width = 9.0
config.frame_height = 16.0

CHINESE_FONT = "{config.chinese_font}"
VIETNAMESE_FONT = "Arial"

class {scene_name}(Scene):
    def construct(self):
        words = {words_code}
        total_words = len(words)
        topic_title = "{clean_topic}"

        # 1. Background Image
        bg_path = "{os.path.join(config.base_dir, 'assets/images/background.jpg')}"
        if os.path.exists(bg_path):
            bg_image = ImageMobject(bg_path)
            bg_image.set_height(config.frame_height)
            bg_image.set_width(config.frame_width)
            self.add(bg_image)
            
        dark_overlay = Rectangle(
            width=config.frame_width,
            height=config.frame_height,
            fill_color="#030712",
            fill_opacity=0.45,
            stroke_width=0
        )
        self.add(dark_overlay)

        # 2. Top Header Pill
        pill_text = Text(
            topic_title.upper(),
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#082f49",
            weight=BOLD
        )
        pill_bg = RoundedRectangle(
            corner_radius=0.35,
            width=max(pill_text.width + 0.8, 3.6),
            height=0.68,
            fill_color="#38bdf8",
            fill_opacity=0.98,
            stroke_color="#7dd3fc",
            stroke_width=1.5
        ).move_to(UP * 6.7)
        pill_text.move_to(pill_bg.get_center())
        header_pill = VGroup(pill_bg, pill_text)

        # 3. Top Mode Box: "Bạn thuộc Pinyin chưa?"
        mode_card = RoundedRectangle(
            corner_radius=0.25,
            width=4.8,
            height=0.9,
            fill_color="#0b0f19",
            fill_opacity=0.88,
            stroke_color="#1e293b",
            stroke_width=1.5
        ).next_to(pill_bg, DOWN, buff=0.22)
        
        mode_title = Text(
            "Bạn thuộc Pinyin chưa?",
            font=VIETNAMESE_FONT,
            font_size=26,
            color="#fbbf24",
            weight=BOLD
        ).move_to(mode_card.get_center())
        
        header_mode = VGroup(mode_card, mode_title)
        self.play(FadeIn(header_pill, shift=DOWN*0.3), FadeIn(header_mode, shift=DOWN*0.3), run_time=0.6)

        # 4. Bottom Footer Floating Card: Logo + "lelehoctiengtrung"
        footer_card = RoundedRectangle(
            corner_radius=0.3,
            width=7.4,
            height=1.25,
            fill_color="#090d16",
            fill_opacity=0.88,
            stroke_color="#1e293b",
            stroke_width=1.5
        ).move_to(DOWN * 6.3)

        avatar_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(avatar_path):
            avatar_img = ImageMobject(avatar_path).set_height(0.85)
            avatar_bg = RoundedRectangle(corner_radius=0.2, width=0.9, height=0.9, fill_color="#0284c7", fill_opacity=0.3, stroke_width=0)
            avatar_group = Group(avatar_bg, avatar_img).move_to(footer_card.get_left() + RIGHT * 0.75)
        else:
            avatar_group = Dot(radius=0.4, color=BLUE_D).move_to(footer_card.get_left() + RIGHT * 0.75)

        footer_title = Text("lelehoctiengtrung", font="sans-serif", font_size=32, color=WHITE, weight=BOLD)
        footer_title.next_to(avatar_group, RIGHT, buff=0.35)

        footer_base = Group(footer_card, avatar_group, footer_title)
        self.play(FadeIn(footer_base, shift=UP*0.3), run_time=0.5)

        # 5. Words Loop
        for idx, w in enumerate(words, start=1):
            hanzi = w["hanzi"]
            pinyin_full = w["pinyin"]
            hidden_py = w["hidden_pinyin"]
            meaning = w["meaning"]
            voice_file = w.get("voice", "")

            # Word counter
            counter_text = Text(f"Từ {{idx}}/{{total_words}}", font=VIETNAMESE_FONT, font_size=26, color="#94a3b8", weight=SEMIBOLD)
            counter_text.move_to(footer_card.get_right() + LEFT * 0.9)
            self.play(FadeIn(counter_text, run_time=0.2))

            # Main Question Card
            center_card = RoundedRectangle(
                corner_radius=0.45,
                width=7.4,
                height=6.6,
                fill_color="#090d16",
                fill_opacity=0.88,
                stroke_color="#1e293b",
                stroke_width=1.5
            ).move_to(UP * 0.3)

            # 1. Chữ tiếng Trung
            hz_text = Text(
                hanzi,
                font=CHINESE_FONT,
                font_size=125,
                color=WHITE,
                weight=BOLD
            ).move_to(center_card.get_top() + DOWN * 1.3)
            if hz_text.width > 6.4:
                hz_text.scale_to_fit_width(6.4)
            
            # 2. Nghĩa tiếng Việt
            meaning_text = Text(
                f"({{meaning}})",
                font=VIETNAMESE_FONT,
                font_size=40,
                color="#94a3b8",
                weight=SEMIBOLD
            ).next_to(hz_text, DOWN, buff=0.28)
            if meaning_text.width > 6.4:
                meaning_text.scale_to_fit_width(6.4)

            # 3. Khu vực chạy Pinyin (Ẩn)
            hidden_text = Text(
                hidden_py,
                font="sans-serif",
                font_size=68,
                color="#facc15",
                weight=BOLD
            ).next_to(meaning_text, DOWN, buff=0.6)
            if hidden_text.width > 6.4:
                hidden_text.scale_to_fit_width(6.4)

            # 4. Countdown 5 giây
            time_label = Text("TIME", font="sans-serif", font_size=30, color="#94a3b8", weight=BOLD)
            timer_num = Text("5", font="sans-serif", font_size=54, color=WHITE, weight=BOLD)
            timer_group = VGroup(time_label, timer_num).arrange(RIGHT, buff=0.25).next_to(hidden_text, DOWN, buff=0.6)

            # Progress Bar Track
            bar_width = 5.4
            bar_track = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#1e293b",
                fill_opacity=0.8,
                stroke_width=0
            ).next_to(timer_group, DOWN, buff=0.35)

            active_bar = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#38bdf8",
                fill_opacity=1.0,
                stroke_width=0
            ).move_to(bar_track.get_center())

            quiz_mobjects = VGroup(center_card, hz_text, meaning_text, hidden_text, timer_group, bar_track, active_bar)
            self.play(FadeIn(quiz_mobjects, shift=UP*0.2), run_time=0.4)

            # Tik audio file
            tick_file = "{os.path.join(config.base_dir, 'assets/audio/tick.mp3')}"

            # 5s countdown
            total_seconds = 5
            for s in range(total_seconds, 0, -1):
                if os.path.exists(tick_file):
                    try:
                        self.add_sound(tick_file)
                    except Exception:
                        pass
                
                fraction_left = (s - 1) / total_seconds
                new_bar_width = max(bar_width * fraction_left, 0.01)
                
                new_active_bar = RoundedRectangle(
                    corner_radius=0.08,
                    width=new_bar_width,
                    height=0.16,
                    fill_color="#38bdf8" if s > 2 else "#f43f5e",
                    fill_opacity=1.0 if s > 1 else 0.0,
                    stroke_width=0
                ).move_to(bar_track.get_center()).align_to(bar_track, LEFT)
                
                display_num = str(s - 1) if s > 1 else "0"
                new_timer_num = Text(display_num, font="sans-serif", font_size=54, color=WHITE if s > 2 else "#f43f5e", weight=BOLD)
                new_timer_num.move_to(timer_num.get_center())

                self.play(
                    Transform(active_bar, new_active_bar),
                    Transform(timer_num, new_timer_num),
                    run_time=0.9,
                    rate_func=linear
                )
                self.wait(0.1)

            # HẾT 5s: Chuông báo kết thúc đếm ngược
            bell_file = "{os.path.join(config.base_dir, 'assets/audio/ding.mp3')}"
            if not os.path.exists(bell_file):
                bell_file = "{config.bell_audio_path}"
            if os.path.exists(bell_file):
                try:
                    self.add_sound(bell_file)
                except Exception:
                    pass

            self.play(FadeOut(timer_group), FadeOut(bar_track), FadeOut(active_bar), run_time=0.15)

            # Hiện Pinyin đầy đủ (tự động co nhỏ font nếu dài quá để vừa khuôn)
            answer_pinyin = Text(
                pinyin_full,
                font="sans-serif",
                font_size=75,
                color="#38bdf8",
                weight=BOLD
            ).move_to(hidden_text.get_center())
            if answer_pinyin.width > 6.4:
                answer_pinyin.scale_to_fit_width(6.4)

            self.play(
                Transform(hidden_text, answer_pinyin),
                run_time=0.45
            )

            # Sau tiếng chuông kết thúc 0.5 giây mới đọc Pinyin (chuông kéo dài 0.85s, animation chạy 0.6s -> chờ thêm 0.75s để đúng 0.5s sau tiếng chuông)
            self.wait(0.75)

            # Phát âm Pinyin (tốc độ chậm rãi, rõ ràng)
            if voice_file and os.path.exists(voice_file):
                try:
                    self.add_sound(voice_file)
                except Exception:
                    pass

            # Giữ 2.2 giây để người xem nghe rõ và đọc theo
            self.wait(2.2)

            # Clear card
            self.play(
                FadeOut(center_card),
                FadeOut(hz_text),
                FadeOut(meaning_text),
                FadeOut(hidden_text),
                FadeOut(counter_text),
                run_time=0.35
            )

        # End Screen CTA - Channel logo ở giữa khung trên của box chữ
        end_card = RoundedRectangle(
            corner_radius=0.45,
            width=7.6,
            height=5.8,
            fill_color="#090d16",
            fill_opacity=0.94,
            stroke_color="#38bdf8",
            stroke_width=2.0
        ).move_to(UP * 0.3)

        logo_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(logo_path):
            logo_img = ImageMobject(logo_path).set_height(1.3)
            logo_bg = RoundedRectangle(
                corner_radius=0.3,
                width=1.45,
                height=1.45,
                fill_color="#0b1120",
                fill_opacity=1.0,
                stroke_color="#38bdf8",
                stroke_width=2.0
            )
            logo_badge = Group(logo_bg, logo_img)
        else:
            logo_badge = Dot(radius=0.6, color="#0284c7")

        end_title = Text("BẠN ĐOÁN ĐÚNG MẤY CÂU?", font=VIETNAMESE_FONT, font_size=34, color="#fbbf24", weight=BOLD)
        end_sub1 = Text("Comment số điểm bên dưới nhé! 👇", font=VIETNAMESE_FONT, font_size=25, color=WHITE)
        end_sub2 = Text("Follow kênh lelehoctiengtrung", font=VIETNAMESE_FONT, font_size=25, color="#38bdf8", weight=BOLD)
        end_sub3 = Text("để luyện tập mỗi ngày! ✨", font=VIETNAMESE_FONT, font_size=24, color="#cbd5e1")
        
        end_text_group = VGroup(end_title, end_sub1, end_sub2, end_sub3).arrange(DOWN, buff=0.25)
        if end_text_group.width > 6.8:
            end_text_group.scale_to_fit_width(6.8)
            
        end_content = Group(logo_badge, end_text_group).arrange(DOWN, buff=0.35)
        end_content.move_to(end_card.get_center())
        
        self.play(FadeIn(end_card), FadeIn(end_content), run_time=0.5)
        self.wait(2.5)
        self.play(FadeOut(end_card), FadeOut(end_content), FadeOut(header_pill), FadeOut(header_mode), FadeOut(footer_base), run_time=0.5)
'''
    return code

def create_scene_file(batch_data: Dict[str, Any], output_path: str = None) -> Tuple[str, str]:
    """Save generated scene code to Python file."""
    os.makedirs(config.generated_scenes_dir, exist_ok=True)
    batch_id = batch_data.get("id", "1")
    topic = batch_data.get("topic", "HSK 1-2 • TỪ VỰNG CƠ BẢN")
    level = batch_data.get("level", "HSK 1-2")
    words_input = batch_data.get("words", [])
    
    scene_name = f"HSKBatch_{re.sub(r'[^a-zA-Z0-9_]', '_', str(batch_id))}"
    code = generate_scene_code(words_input, topic, level, scene_name)
    
    if not output_path:
        output_path = os.path.join(config.generated_scenes_dir, f"scene_batch_{batch_id}.py")
        
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(code)
        
    return output_path, scene_name
