import os
import re
from typing import List, Dict, Any, Tuple
from src.config import config
from src.pinyin_utils import prepare_word_tuple
from src.audio_generator import generate_chinese_voice

def generate_scene_code(
    words: List[Dict[str, Any]],
    topic: str = "HSK 1-2 • TỪ VỰNG CƠ BẢN",
    level: str = "HSK 1-2",
    scene_name: str = "ModernVocabVNQuizScene",
    cover_path: str = ""
) -> str:
    """
    Generates standalone Python/Manim script code for VocabVNQuiz:
    Hero Question: Vietnamese Meaning -> 🇻🇳 ➔ 🇨🇳 -> 5s Countdown -> Reveal Chinese Hanzi + Pinyin + Audio TTS.
    """
    clean_topic = topic.replace('"', '\\"')
    
    words_data = []
    for item in words:
        if isinstance(item, dict):
            h = item.get("hanzi", "")
            fp = item.get("pinyin", "")
            hp = item.get("hidden_pinyin", "")
            m = item.get("meaning", "")
        elif isinstance(item, (list, tuple)):
            h = item[0] if len(item) > 0 else ""
            fp = item[1] if len(item) > 1 else ""
            hp = item[2] if len(item) > 2 else ""
            m = item[3] if len(item) > 3 else ""
        else:
            continue
            
        if h:
            if not fp or not hp:
                _, fp_calc, hp_calc = prepare_word_tuple(h, fp, hp)
                fp = fp or fp_calc
                hp = hp or hp_calc
                
            voice_path = generate_chinese_voice(h)
            words_data.append({
                "hanzi": h,
                "pinyin": fp,
                "hidden_pinyin": hp,
                "meaning": m or h,
                "voice": voice_path
            })
            
    words_code = repr(words_data)
    
    code = f'''# Auto-generated by lelehoctiengtrung VocabVNquiz scene generator
from manim import *
import os

config.pixel_width = 1080
config.pixel_height = 1920
config.frame_width = 9.0
config.frame_height = 16.0

CHINESE_FONT = "{config.chinese_font}"
VIETNAMESE_FONT = "Arial"

class {scene_name}(Scene):
    def construct(self):
        words = {words_code}
        total_words = len(words)
        topic_title = "{clean_topic}"

        # 0. High-CTR Cover Thumbnail (0.75s Cover at 00:00 for TikTok / Shorts / Reels)
        cover_path = "{cover_path}"
        if os.path.exists(cover_path):
            cover_img = ImageMobject(cover_path)
            cover_img.set_height(config.frame_height)
            cover_img.set_width(config.frame_width)
            self.add(cover_img)
            self.wait(0.75)
            self.remove(cover_img)

        # 1. Top Header Pill
        pill_text = Text(
            topic_title.upper(),
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#451a03",
            weight=BOLD
        )
        pill_bg = RoundedRectangle(
            corner_radius=0.35,
            width=max(pill_text.width + 0.8, 3.6),
            height=0.68,
            fill_color="#f59e0b",
            fill_opacity=0.98,
            stroke_color="#fcd34d",
            stroke_width=1.5
        ).move_to(UP * 6.7)
        pill_text.move_to(pill_bg.get_center())
        header_pill = VGroup(pill_bg, pill_text)

        # 2. Top Mode Box: "TIẾNG TRUNG TRONG 5S"
        mode_card = RoundedRectangle(
            corner_radius=0.25,
            width=5.2,
            height=0.9,
            fill_color="#0b0f19",
            fill_opacity=0.88,
            stroke_color="#f59e0b",
            stroke_width=1.5
        ).next_to(pill_bg, DOWN, buff=0.22)
        
        mode_title = Text(
            "TIẾNG TRUNG TRONG 5S",
            font=VIETNAMESE_FONT,
            font_size=26,
            color="#fbbf24",
            weight=BOLD
        ).move_to(mode_card.get_center())
        
        header_mode = VGroup(mode_card, mode_title)
        self.play(FadeIn(header_pill, shift=DOWN*0.3), FadeIn(header_mode, shift=DOWN*0.3), run_time=0.6)

        # 3. Bottom Footer Floating Card: Logo + "lelehoctiengtrung"
        footer_card = RoundedRectangle(
            corner_radius=0.3,
            width=7.4,
            height=1.25,
            fill_color="#090d16",
            fill_opacity=0.88,
            stroke_color="#1e293b",
            stroke_width=1.5
        ).move_to(DOWN * 6.3)

        avatar_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(avatar_path):
            avatar_img = ImageMobject(avatar_path).set_height(0.85).move_to(footer_card.get_left() + RIGHT * 0.75)
        else:
            avatar_img = Dot(radius=0.4, color=YELLOW_E).move_to(footer_card.get_left() + RIGHT * 0.75)

        footer_title = Text("lelehoctiengtrung", font=VIETNAMESE_FONT, font_size=32, color=WHITE, weight=BOLD)
        footer_title.next_to(avatar_img, RIGHT, buff=0.35)

        self.play(FadeIn(footer_card, shift=UP*0.3), FadeIn(avatar_img), FadeIn(footer_title, shift=UP*0.3), run_time=0.5)

        # 4. Words Loop
        for idx, w in enumerate(words, start=1):
            hanzi = w["hanzi"]
            pinyin_full = w["pinyin"]
            meaning = w["meaning"]
            voice_file = w.get("voice", "")

            # Word counter
            icon_suffix = " ⚡" if idx == 4 else (" 🔥" if idx == 5 else "")
            counter_color = "#fbbf24" if idx == 4 else ("#f87171" if idx == 5 else "#94a3b8")
            counter_text = Text(
                f"Từ {{idx}}/{{total_words}}{{icon_suffix}}",
                font=VIETNAMESE_FONT,
                font_size=26,
                color=counter_color,
                weight=BOLD if idx >= 4 else SEMIBOLD
            )
            counter_text.move_to(footer_card.get_right() + LEFT * 1.0)
            self.play(FadeIn(counter_text, run_time=0.2))

            # Main Question Card
            center_card = RoundedRectangle(
                corner_radius=0.45,
                width=7.4,
                height=6.8,
                fill_color="#090d16",
                fill_opacity=0.88,
                stroke_color="#f59e0b",
                stroke_width=1.8
            ).move_to(UP * 0.3)

            # Flags: 🇻🇳 ➔ 🇨🇳 (Quốc kỳ to hơn dấu mũi tên)
            flag_vn_path = "{os.path.join(config.base_dir, 'assets/images/flag_vn.png')}"
            flag_cn_path = "{os.path.join(config.base_dir, 'assets/images/flag_cn.png')}"
            
            flag_vn = ImageMobject(flag_vn_path).set_height(0.85) if os.path.exists(flag_vn_path) else Dot(color=RED)
            flag_cn = ImageMobject(flag_cn_path).set_height(0.85) if os.path.exists(flag_cn_path) else Dot(color=YELLOW)
            arrow_icon = Text("➔", font="Arial", font_size=42, color="#f59e0b", weight=BOLD)
            
            flag_group = Group(flag_vn, arrow_icon, flag_cn).arrange(RIGHT, buff=0.40).move_to(center_card.get_top() + DOWN * 1.15)

            # 1. Question Hero: Nghĩa Tiếng Việt
            vn_text = Text(
                meaning,
                font=VIETNAMESE_FONT,
                font_size=78,
                color=WHITE,
                weight=BOLD
            ).next_to(flag_group, DOWN, buff=0.45)
            if vn_text.width > 6.4:
                vn_text.scale_to_fit_width(6.4)

            # 2. Countdown 5 giây
            time_label = Text("TIME", font=VIETNAMESE_FONT, font_size=30, color="#94a3b8", weight=BOLD)
            timer_num = Text("5", font=VIETNAMESE_FONT, font_size=54, color=WHITE, weight=BOLD)
            timer_group = VGroup(time_label, timer_num).arrange(RIGHT, buff=0.25).next_to(vn_text, DOWN, buff=0.55)

            # Progress Bar Track
            bar_width = 5.4
            bar_track = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#1e293b",
                fill_opacity=0.8,
                stroke_width=0
            ).next_to(timer_group, DOWN, buff=0.35)

            active_bar = RoundedRectangle(
                corner_radius=0.08,
                width=bar_width,
                height=0.16,
                fill_color="#f59e0b",
                fill_opacity=1.0,
                stroke_width=0
            ).move_to(bar_track.get_center())

            # Intro question elements
            self.play(
                FadeIn(center_card, shift=UP*0.3),
                FadeIn(flag_group),
                FadeIn(vn_text, shift=UP*0.2),
                FadeIn(timer_group),
                FadeIn(bar_track),
                FadeIn(active_bar),
                run_time=0.5
            )

            # Tick sound path
            tick_sound = "{os.path.join(config.base_dir, 'assets/audio/tick.mp3')}"
            bell_sound = "{os.path.join(config.base_dir, 'assets/audio/ding.mp3')}"

            # Countdown 5..4..3..2..1 (5s total)
            for c_sec in range(5, 0, -1):
                if c_sec < 5:
                    new_timer_num = Text(str(c_sec), font=VIETNAMESE_FONT, font_size=54, color="#fbbf24" if c_sec <= 2 else WHITE, weight=BOLD).move_to(timer_num.get_center())
                    self.remove(timer_num)
                    self.add(new_timer_num)
                    timer_num = new_timer_num
                
                # Tick sound
                if os.path.exists(tick_sound):
                    try:
                        self.add_sound(tick_sound)
                    except Exception:
                        pass
                
                # Shrink active bar
                target_ratio = (c_sec - 1) / 5.0
                target_w = max(0.01, bar_width * target_ratio)
                new_bar = RoundedRectangle(
                    corner_radius=0.08,
                    width=target_w,
                    height=0.16,
                    fill_color="#f59e0b",
                    fill_opacity=1.0,
                    stroke_width=0
                ).align_to(bar_track, LEFT)
                
                self.play(
                    Transform(active_bar, new_bar),
                    run_time=1.0,
                    rate_func=linear
                )

            # Bell chime at reveal
            if os.path.exists(bell_sound):
                try:
                    self.add_sound(bell_sound)
                except Exception:
                    pass

            # Fade out countdown
            self.play(
                FadeOut(timer_group),
                FadeOut(bar_track),
                FadeOut(active_bar),
                run_time=0.2
            )

            # Reveal Chinese: Hanzi Big + Pinyin
            ans_hanzi = Text(
                hanzi,
                font=CHINESE_FONT,
                font_size=115,
                color="#f59e0b",
                weight=BOLD
            ).move_to(center_card.get_center() + DOWN * 0.3)
            if ans_hanzi.width > 6.4:
                ans_hanzi.scale_to_fit_width(6.4)

            ans_pinyin = Text(
                pinyin_full,
                font=VIETNAMESE_FONT,
                font_size=60,
                color=WHITE,
                weight=BOLD
            ).next_to(ans_hanzi, DOWN, buff=0.35)
            if ans_pinyin.width > 6.4:
                ans_pinyin.scale_to_fit_width(6.4)

            reveal_group = VGroup(ans_hanzi, ans_pinyin)
            self.play(FadeIn(reveal_group, shift=UP*0.2), run_time=0.45)

            self.wait(0.75)

            if voice_file and os.path.exists(voice_file):
                try:
                    self.add_sound(voice_file)
                except Exception:
                    pass

            self.wait(2.2)

            # Clear card
            self.play(
                FadeOut(center_card),
                FadeOut(flag_group),
                FadeOut(vn_text),
                FadeOut(reveal_group),
                FadeOut(counter_text),
                run_time=0.35
            )

        # End Screen CTA
        end_card = RoundedRectangle(
            corner_radius=0.45,
            width=7.6,
            height=5.8,
            fill_color="#090d16",
            fill_opacity=0.94,
            stroke_color="#f59e0b",
            stroke_width=2.0
        ).move_to(UP * 0.3)

        logo_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(logo_path):
            logo_img = ImageMobject(logo_path).set_height(1.4).move_to(end_card.get_top() + DOWN * 1.1)
        else:
            logo_img = Dot(radius=0.6, color=YELLOW_E).move_to(end_card.get_top() + DOWN * 1.1)

        end_title = Text(
            "BẠN ĐÚNG MẤY TỪ?",
            font=VIETNAMESE_FONT,
            font_size=42,
            color="#fbbf24",
            weight=BOLD
        ).next_to(logo_img, DOWN, buff=0.35)

        end_cta = Text(
            "Bình luận số câu đúng bên dưới nhé! 👇",
            font=VIETNAMESE_FONT,
            font_size=28,
            color=WHITE,
            weight=SEMIBOLD
        ).next_to(end_title, DOWN, buff=0.25)

        end_sub = Text(
            "Follow @lelehoctiengtrung để học mỗi ngày 🚀",
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#94a3b8",
            weight=NORMAL
        ).next_to(end_cta, DOWN, buff=0.35)

        self.play(
            FadeIn(end_card, shift=UP*0.3),
            FadeIn(logo_img),
            FadeIn(end_title, shift=UP*0.2),
            FadeIn(end_cta, shift=UP*0.2),
            FadeIn(end_sub, shift=UP*0.2),
            run_time=0.6
        )
        self.wait(2.5)
'''
    return code

def create_scene_file(
    words: List[Dict[str, Any]],
    topic: str,
    level: str,
    output_py_path: str,
    scene_name: str = "ModernVocabVNQuizScene",
    cover_path: str = ""
) -> str:
    """Writes scene code to a .py file and returns the path."""
    os.makedirs(os.path.dirname(output_py_path), exist_ok=True)
    code = generate_scene_code(words, topic, level, scene_name, cover_path)
    with open(output_py_path, "w", encoding="utf-8") as f:
        f.write(code)
    return output_py_path
